# Generated by Django 2.1.15 on 2023-10-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_creator', models.CharField(max_length=30)),
                ('recipe_published_date', models.DateTimeField(verbose_name='recipe date')),
                ('cuisine', models.CharField(max_length=200)),
                ('cooking_time', models.FloatField()),
            ],
        ),
    ]
