# Generated by Django 2.1.15 on 2023-10-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='recipes',
            name='course',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main', 'Main'), ('Sides', 'Sides'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Drinks', 'Drinks'), ('Vegetarian', 'Vegetarian')], default='Starters', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_published_date',
            field=models.DateField(verbose_name='recipe published date'),
        ),
    ]
