# Generated by Django 2.1.15 on 2023-10-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20231025_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_published_date',
            field=models.DateTimeField(verbose_name='Recipe Published Date'),
        ),
    ]
