# Generated by Django 4.2.6 on 2023-11-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20231026_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_description',
            field=models.TextField(default='No description available'),
        ),
        migrations.AddField(
            model_name='recipes',
            name='recipe_pic',
            field=models.ImageField(default='default_recipe_image.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='course',
            field=models.CharField(choices=[('Starters', 'Starters'), ('Main', 'Main'), ('Sides', 'Sides'), ('Dessert', 'Dessert'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Drinks', 'Drinks'), ('Vegetarian', 'Vegetarian')], max_length=200),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_published_date',
            field=models.DateField(verbose_name='Recipe Published Date'),
        ),
    ]
